### ISSUE TITLE
Refactor All css classes to main css file 

### ISSUE THREAD

**Issue by Shehanka** [sliit-foss/sliitfoss#109]
@Sewvandiii Is it possible to get help from your team

**Comment by carlitos-0411** [comment]
i want to do this pls guide me a bit

**Comment by Safnaj** [comment]
> i want to do this pls guide me a bit

We have some reusable css classes which is already written inside components. We have to identify those and move to main CSS file

**Comment by carlitos-0411** [comment]
Sir pls review it whether i have done it correct or not

**Comment by Shehanka** [comment]
> Sir pls review it whether i have done it correct or not

I've given a review in the PR.
