### ISSUE TITLE
RSVP for event registration

### ISSUE THREAD

**Issue by Safnaj** [sliit-foss/sliitfoss#11]
Need a backend service for event registration. The system will be used for the upcoming event registration at SLIIT.

Technology : Node.js

**Comment by lwpamihiranga** [comment]
@Safnaj I can give a hand if needed :)

**Comment by Safnaj** [comment]
Can u design the RSVP page ??
so we can start the backend later..

**Comment by lwpamihiranga** [comment]
my designs are not great. thought to help with NodeJS.  but I can try. do you guys have any sketch or some guideline on what should be included?

**Comment by Shehanka** [comment]
@Indimagedara you can help us to develop the backend. 

CC: @ebonynon Take him to backend dev team

**Comment by ebonynon** [comment]
Hello @lwpamihiranga, Welcome to the backend dev team. I will assign you tasks when the project was begun.

**Comment by Safnaj** [comment]
@ebonynon Refer the below fields when designing the DB

### Event
ID
Name
Date & Time
Description
Speaker
Image
Status (Open/Closed)

### Users
ID
Name
Email
Contact Number

**Comment by Safnaj** [comment]
@Shehanka @ebonynon i thing its good to go with another repo for rsvp-frontend.
Once it deployed we can link it to our foss website.
