### ISSUE TITLE
Carousel auto slide not working

### ISSUE THREAD

**Issue by Safnaj** [sliit-foss/sliitfoss#111]
Past Events carousel slider not auto sliding.

**Comment by Aiwwa** [comment]
Hi, i can try to solve this problem :)

**Comment by Shehanka** [comment]
> Hi, i can try to solve this problem :)

@Aiwwa , Okay then Can you fix it and send us a Pull Request?

**Comment by Shehanka** [comment]
Any update on this @Aiwwa

**Comment by Safnaj** [comment]
@Shehanka is this fixed ?

**Comment by Shehanka** [comment]
> @Shehanka is this fixed ?

Yes
