### ISSUE TITLE
UI Fixes before MVP release

### ISSUE THREAD

**Issue by Shehanka** [sliit-foss/sliitfoss#114]
[ ] Space in bottom (Contact Page)
![image](https://user-images.githubusercontent.com/19349315/106114276-62b48e00-6175-11eb-885c-4d9db8349b6b.png)

**Comment by Safnaj** [comment]
- [ ] Responsive Issue in Home Page 
- [ ] Past Events Carousel not center align in responsive
- [ ] Pagination not working in blogs component
- [ ] Contact Form not working

**Comment by Shehanka** [comment]
@Bawanthathilan @nisalrenuja @KaveeshaG  What's the update on this?

**Comment by Shehanka** [comment]
@Bawanthathilan fix everything

**Comment by Bawanthathilan** [comment]
> @Bawanthathilan fix everything 
> 
> 

Am I a god to fix everything ? 🙃

**Comment by Shehanka** [comment]
CSS God
