### ISSUE TITLE
Style Upcoming Event Component

### ISSUE THREAD

**Issue by Safnaj** [sliit-foss/sliitfoss#133]
Upcoming events component need to be more styled.

- [x] Add More Outer Shadow
- [ ] Proper Button Design for Register
- [ ] Remove blank space between image & Description

**Comment by Shehanka** [comment]
@ebonynon @nisalrenuja

**Comment by SahasR** [comment]
Also are the 'LIKE' and 'SHARE' buttons necessary? (They currently are unlinked as well)

**Comment by ebonynon** [comment]
> Also are the 'LIKE' and 'SHARE' buttons necessary? (They currently are unlinked as well)

I don't think so

**Comment by nisalrenuja** [comment]
![Capture](https://user-images.githubusercontent.com/42801983/106234936-af54a380-621f-11eb-9494-d69734dee24b.PNG)

**Comment by Shehanka** [comment]
comment like and share button

**Comment by Safnaj** [comment]
- [ ] Change the event name to right side above the description.
- [ ] Remove the gap between image and description
- [ ] Keep only the register button

**Comment by nisalrenuja** [comment]
> comment like and share button

I removed like and share button. Is it okay??

**Comment by nisalrenuja** [comment]
![Capture](https://user-images.githubusercontent.com/42801983/106237153-3146cb80-6224-11eb-8a9a-2abf6af99491.PNG)

**Comment by Safnaj** [comment]
@nisalrenuja Button seems big. Use the same button in home page. Rounded one..!

Also and some line height space. Refer about page contents

**Comment by nisalrenuja** [comment]
![Uploading Capture.PNG…]()

**Comment by nisalrenuja** [comment]
![Capture](https://user-images.githubusercontent.com/42801983/106238517-00b46100-6227-11eb-835d-b1574a27db4c.PNG)

**Comment by nisalrenuja** [comment]
Register button made same as in-home page

**Comment by nisalrenuja** [comment]
![Capture](https://user-images.githubusercontent.com/42801983/106249633-9efcf280-6238-11eb-8f44-6477bd79d931.PNG)

**Comment by nisalrenuja** [comment]
@Safnaj Change I finished 
- Add More Outer Shadow,
- the event name to the right side above the description,  
- Keep only the register button

**Comment by Safnaj** [comment]
![image](https://user-images.githubusercontent.com/37530024/106273622-fa3edd00-6258-11eb-9d48-5657c81a3996.png)

Remove these spaces

**Comment by Safnaj** [comment]
Remove these white spaces

<img width="1440" alt="Screenshot 2021-01-29 at 5 39 06 PM" src="https://user-images.githubusercontent.com/37530024/106273673-117dca80-6259-11eb-974c-f64df00ee768.png">

**Comment by chenukas** [comment]
@Shehanka this is also fixed I think. Better to re-check and close this issue or request changes.
