### ISSUE TITLE
"Contribution Guideline" and "Brand Assets" Unlinked 

### ISSUE THREAD

**Issue by SahasR** [sliit-foss/sliitfoss#138]
"Contribution Guideline" and "Brand Assets" Unlinked in the Footer

**Comment by Shehanka** [comment]
@SahasR can u work on this?

**Comment by SahasR** [comment]
I'll give it a shot, are the pages in the directory?

**Comment by Shehanka** [comment]
https://github.com/sliit-foss/brand-assets/tree/master/Logo%20Guidelines
@ebonynon give him contributions guidelines
