### ISSUE TITLE
Navbar Component with Curved Design

### ISSUE THREAD

**Issue by Safnaj** [sliit-foss/sliitfoss#15]
The navbar have to designed as described in the below image. Can go with pure css or flex SVG to accomplish this.
The logo can be found in asset folder.

<img width="1383" alt="Screenshot 2020-10-13 at 5 43 21 PM" src="https://user-images.githubusercontent.com/37530024/95859092-b42e3e00-0d7b-11eb-80d2-c873272cb91c.png">

**Comment by Safnaj** [comment]
@Shehanka can u share the curved image as PNG ?? so i can try with some CSS codes.

**Comment by Kushiya** [comment]
<img width="428" alt="Rectangle 1" src="https://user-images.githubusercontent.com/36870065/96219438-7829f180-0fa4-11eb-8ff2-3eea50a6e3c9.png">

**Comment by Shehanka** [comment]
@Safnaj you can take curved design from her

**Comment by Safnaj** [comment]
I requested Shafkhan to do this. Now updates from him yet.

**Comment by Shehanka** [comment]
> I requested Shafkhan to do this. Now updates from him yet.

Great! 👍🏻

**Comment by Safnaj** [comment]
Can someone ask this question on StackOverflow ?

**Comment by Bawanthathilan** [comment]
![Screenshot_2020-10-28 SLIIT FOSS](https://user-images.githubusercontent.com/38850236/97464116-8396f880-1966-11eb-907c-3f4628101bba.png)

**Comment by Shehanka** [comment]
@Bawanthathilan PR ekak dapn

**Comment by Safnaj** [comment]
> @Bawanthathilan PR ekak dapn

Chamod check the site again.. seems the curved design is too small and having a margin in left side.
