### ISSUE TITLE
New Footer UI issue

### ISSUE THREAD

**Issue by Shehanka** [sliit-foss/sliitfoss#163]
![image](https://user-images.githubusercontent.com/19349315/106311487-3e4ad580-628b-11eb-9756-5ad83980023a.png)

make Text decoration none for links
![image](https://user-images.githubusercontent.com/19349315/106311515-473ba700-628b-11eb-98fe-8d4eb234adfc.png)

**Comment by Safnaj** [comment]
is this fixed ?

**Comment by Shehanka** [comment]
> is this fixed ?

Yes

**Comment by Safnaj** [comment]
Fixed via #202
