### ISSUE TITLE
Home Page UI issues 

### ISSUE THREAD

**Issue by Shehanka** [sliit-foss/sliitfoss#165]
![image](https://user-images.githubusercontent.com/19349315/106312741-26745100-628d-11eb-9e1a-1002ef9cc927.png)

Shape overlapping 
![image](https://user-images.githubusercontent.com/19349315/106312785-38ee8a80-628d-11eb-8abe-e0d14a62e39d.png)
![image](https://user-images.githubusercontent.com/19349315/106312814-4441b600-628d-11eb-9e4a-36a9a9d70d46.png)

![image](https://user-images.githubusercontent.com/19349315/106312831-4ad02d80-628d-11eb-934e-4c494985bdc0.png)

![image](https://user-images.githubusercontent.com/19349315/106312864-558ac280-628d-11eb-93dc-10cb5eecd8a3.png)

**Comment by Bawanthathilan** [comment]
@Shehanka 
https://github.com/sliit-foss/sliitfoss/pull/171#pullrequestreview-579737455

**Comment by Safnaj** [comment]
@Bawanthathilan @Shehanka can we close this issue ?

**Comment by Shehanka** [comment]
> @Bawanthathilan @Shehanka can we close this issue ?
> 
> 

Lemme close it
