### ISSUE TITLE
Event Page UI issues 

### ISSUE THREAD

**Issue by Shehanka** [sliit-foss/sliitfoss#166]
![image](https://user-images.githubusercontent.com/19349315/106313000-87038e00-628d-11eb-86bd-684c1184264d.png)

**Comment by Dilshan97** [comment]
fixed [https://github.com/sliit-foss/sliitfoss/pull/176](https://github.com/sliit-foss/sliitfoss/pull/176)

**Comment by Shehanka** [comment]
@Bawanthathilan Can you verify this.
