### ISSUE TITLE
Site Performance : Serve the static content via the cache such as CDN or cache policy

### ISSUE THREAD

**Issue by sajeetharan** [sliit-foss/sliitfoss#179]
There are more than 1MB of resources/assets which are being requested and loaded from the server, implement a cache policy  in the browser for static assets or serve it via CDN in order to improve the performance.

use lighthouse to determine the errors https://developers.google.com/web/tools/lighthouse/

**Comment by Safnaj** [comment]
@sajeetharan Pls Review #251

**Comment by sajeetharan** [comment]
how come this is closed?

**Comment by Safnaj** [comment]
> how come this is closed?

Can you check #251 ??

**Comment by sajeetharan** [comment]
@Safnaj is not it already merged?
