### ISSUE TITLE
Site Performance : Removed unused JS/CSS files

### ISSUE THREAD

**Issue by sajeetharan** [sliit-foss/sliitfoss#180]
There are more than 4 files which are being loaded but unused, try to remove them from the build/source

https://sliitfoss.org/styles.f29e9a2465f405c18f93.css
https://sliitfoss.org/assets/vendor/icofont/icofont.min.css
https://sliitfoss.org/main-es2015.a43811df922492bba323.js
https://sliitfoss.org/scripts.568694a568f45ab03c95.js

**Comment by Safnaj** [comment]
@Bawanthathilan can u have a look ?

**Comment by Shehanka** [comment]
@nisalrenuja can you?

**Comment by sajeetharan** [comment]
@Safnaj @Shehanka can you?
