### ISSUE TITLE
Suggest a good Google font

### ISSUE THREAD

**Issue by Shehanka** [sliit-foss/sliitfoss#19]

**Comment by Kushiya** [comment]
https://fonts.google.com/specimen/Work+Sans?query=work
https://fonts.google.com/specimen/Work+Sans?query=work
https://fonts.google.com/specimen/Work+Sans?query=work
https://fonts.google.com/specimen/Sora?query=sora
https://fonts.google.com/specimen/Syne?query=syne
https://fonts.google.com/specimen/Kumbh+Sans?query=kumbh
https://fonts.google.com/specimen/Epilogue?query=epil
https://fonts.google.com/specimen/Jost?query=jost

**Comment by Sewvandiii** [comment]
https://fonts.google.com/specimen/Baloo+Thambi+2?query=bal&selection.family=Baloo+Thambi+2 👌

**Comment by Shehanka** [comment]
> https://fonts.google.com/specimen/Baloo+Thambi+2?query=bal&selection.family=Baloo+Thambi+2

@Sewvandiii Thambi? 😂
