### ISSUE TITLE
Site Route issue 

### ISSUE THREAD

**Issue by Safnaj** [sliit-foss/sliitfoss#193]
Site is not working properly and not routing to home component in the path /

![Screenshot 2021-02-04 at 6 32 19 PM](https://user-images.githubusercontent.com/37530024/106896274-5bfabd80-6717-11eb-956e-df5f442566ea.png)

**Comment by Safnaj** [comment]
@Dilshan97. This cause after the 404 component implementation. 
Can you check ur local project and also with the latest changes with the Repo.

### Urgent

**Comment by Dilshan97** [comment]
@Safnaj my local project working without any error
![image](https://user-images.githubusercontent.com/27553144/106900178-37551480-671c-11eb-93c3-38255eb91a73.png)

**Comment by Safnaj** [comment]
@Dilshan97 Oh.. It was reactive form issue. Lets see once the PR #194 Merged

**Comment by Dilshan97** [comment]
@Safnaj ok brother
