### ISSUE TITLE
Make the Contact Us form works

### ISSUE THREAD

**Issue by Safnaj** [sliit-foss/sliitfoss#209]

**Comment by Dilshan97** [comment]
@Safnaj how can we create the contact us form?

**Comment by Safnaj** [comment]
> @Safnaj how can we create the contact us form?

In Our GitHub Community Website @ebonynon has implemented the contact us form with out the Back-end. 
We can go with that option. Check this [Repo](https://github.com/GitHubExperts-LK/GitHubExperts-LK.github.io)

**Comment by Safnaj** [comment]
@Shehanka, can we implement a nodemailer function for our contact form in our existing APIs ??

**Comment by Safnaj** [comment]
Any Updates ??

**Comment by Shehanka** [comment]
@chenukas can you work on this?
