### ISSUE TITLE
Resize Vector Images in the Home Page

### ISSUE THREAD

**Issue by Safnaj** [sliit-foss/sliitfoss#219]
![Screenshot 2021-04-17 at 5 27 39 PM](https://user-images.githubusercontent.com/37530024/115112240-3ce39c00-9fa2-11eb-86d2-b48a7d3e5e58.png)

![Screenshot 2021-04-17 at 5 27 58 PM](https://user-images.githubusercontent.com/37530024/115112246-42d97d00-9fa2-11eb-99ca-2706af3384b9.png)

**Comment by Safnaj** [comment]
@Bawanthathilan

**Comment by Bawanthathilan** [comment]
> @Bawanthathilan

https://github.com/sliit-foss/sliitfoss/pull/228

**Comment by Safnaj** [comment]
Fixed via #231
