### ISSUE TITLE
EVENTS: Reduce the gap between cards

### ISSUE THREAD

**Issue by KaveeshaG** [sliit-foss/sliitfoss#239]
**Reduce the gap between cards in Home**
Events -> Past Events && Webinars sections
Check the image reference given below
![bug3](https://user-images.githubusercontent.com/36946467/116783784-56aad600-aaae-11eb-8564-48a2a19331ca.png)

**Comment by Safnaj** [comment]
@KaveeshaG I think you have browser cache issue.
Try Ctrl+Shift+R
