### ISSUE TITLE
BOARD: Check the topic of the Board Page

### ISSUE THREAD

**Issue by KaveeshaG** [sliit-foss/sliitfoss#241]
**Check the Typography of Board page topic**
Board->Board of Officials - 2020/21
Check the image references given below.
![bug5](https://user-images.githubusercontent.com/36946467/116783930-257ed580-aaaf-11eb-98e6-e8222605610a.png)

**Comment by chenukas** [comment]
@KaveeshaG I can't see this issue in my browser neh

**Comment by Safnaj** [comment]
<img width="1414" alt="Screenshot 2021-05-01 at 7 42 17 PM" src="https://user-images.githubusercontent.com/37530024/116785094-582bcc80-aab5-11eb-87c7-95e58025fdd0.png">

Everything fine..!
