### ISSUE TITLE
Make Site Contents 100% 

### ISSUE THREAD

**Issue by Shehanka** [sliit-foss/sliitfoss#244]

**Comment by Safnaj** [comment]
@Sewvandiii Reminder..!!

**Comment by Shehanka** [comment]
@Safnaj she's busy today. She'll do it tomorrow

**Comment by chenukas** [comment]
@Shehanka @Sewvandiii What happened to this? Hope it's done right?

**Comment by Shehanka** [comment]
@chenukas I think so
