### ISSUE TITLE
Year Wise Board Members

### ISSUE THREAD

**Issue by Safnaj** [sliit-foss/sliitfoss#247]
Need to have Years in the components and users able to see the Board for the Particular Year. 
It will be a good documentation for us.

- [x] - 2018
- [x] - 2019
- [x] - 2020
- [x] - 2021

**Comment by Shehanka** [comment]
I'll complete this ASAP

**Comment by Safnaj** [comment]
@Shehanka i think we can close the issue.. The feature has already done. We have to add the board details to the json file only. If you can work on #255 & #256

**Comment by Safnaj** [comment]
@Shehanka when can u complete this ?
