### ISSUE TITLE
Content animations on landing page

### ISSUE THREAD

**Issue by EANimesha** [sliit-foss/sliitfoss#25]
I suggest to add animation to contents when page is loading.
Ex: 
- Vector image Slide from right
- Top content slide from left
- grow in and out the "become a member" button

**Comment by Shehanka** [comment]
@EANimesha Could you please suggest a one! 
cc: @Bawanthathilan @Kushiya @Sewvandiii

**Comment by Kushiya** [comment]
Check this out > lottiefiles.com 
Bit advance but shape and nice 😍

**Comment by Safnaj** [comment]
Anyone working on this ?

**Comment by Shehanka** [comment]
seems like no one

**Comment by Safnaj** [comment]
@Shehanka to whom we can assign this ?? who had experience with this ?

**Comment by Shehanka** [comment]
@nisalrenuja 👀

**Comment by Safnaj** [comment]
@Bawanthathilan Can you ?
