### ISSUE TITLE
Board Members Details : 2018

### ISSUE THREAD

**Issue by Safnaj** [sliit-foss/sliitfoss#255]
Get the board members details for the year 2018 and in the below json file

https://github.com/sliit-foss/sliitfoss/blob/master/src/assets/data/board.json

**Comment by Shehanka** [comment]
Valuka Secretary
Ishan Vice President. 
Thaveesha Treasurer. 
@Nimesh Indimagedara Asst. Treasurer. 
@Kushantha Charuka editor. 
Theekshana Asst. Secretary
