### ISSUE TITLE
Naming Convention of Components

### ISSUE THREAD

**Issue by Safnaj** [sliit-foss/sliitfoss#30]
The naming conventions of components should be understandable to give the idea simple to the new contributors.
The following components should be changed with proper names.

- ceo
- count
- member
- we-do

@Shehanka if possible modify the Readme.md file with set of instructions to follow.

**Comment by Shehanka** [comment]
Sure. I'll do that

**Comment by Safnaj** [comment]
@Shehanka if possible assign a person to rename the components. You can add the author who made it.

**Comment by Shehanka** [comment]
@ebonynon over to u

**Comment by Safnaj** [comment]
Any Updates ??

**Comment by Safnaj** [comment]
@Shehanka @ebonynon Reminder..!
