### ISSUE TITLE
Change GitHub Primer to Bootstrap

### ISSUE THREAD

**Issue by Safnaj** [sliit-foss/sliitfoss#31]
I have identified the following problems when using prettier :

- Time consuming to refer the Documentation all the time
- It's still have some untouched area and bugs.
- Responsive issues.

Since the bootstrap is very famous and familiar, we can get more contributors.

**Comment by Shehanka** [comment]
Be like Apple!! do things differently. First people hated notch design then everyone starts copying it 😉 
Honestly, we don't get many contributions after Hacktoberfest ends. 

Let's get a vote. People who like to try our GitHub primer like this commend and people who don't like it dislike this.

**Comment by Safnaj** [comment]
I agreed. We can learn new stuffs by working on projects. But here i want our website to be published as quicker as possible. 
I almost remember all the bootstrap classes and it is easy to code. Yesterday i was spending much time on documentation rather on the site.

**Comment by Shehanka** [comment]
@Safnaj okay then can you do the change and send me the PR.
