### ISSUE TITLE
New Board Details - 2022/23

### ISSUE THREAD

**Issue by Safnaj** [sliit-foss/sliitfoss#326]
Add details of board members

**Comment by Akalanka47000** [comment]
Database updated with the new member details

**Comment by Safnaj** [comment]
Data need to be updated here
https://github.com/sliit-foss/sliitfoss/blob/master/src/assets/data/board.json

Not only selectedYear value

**Comment by Akalanka47000** [comment]
Data is loaded from firebase now therefore didn't update over here

**Comment by Akalanka47000** [comment]
Sure, will look into it
