### ISSUE TITLE
Make menu font color white in dark mode

### ISSUE THREAD

**Issue by Shehanka** [sliit-foss/sliitfoss#356]
**Is your feature request related to a problem? Please describe.**
It would be a great menu font color change to white in dark mode
**Describe the solution you'd like**

![Screenshot 2022-05-20 at 11 02 10](https://user-images.githubusercontent.com/19349315/169457441-28b4f70f-d329-4152-9a60-26e17fe0af9c.png)

**Comment by Akalanka47000** [comment]
Will have a look
