### ISSUE TITLE
Reduce the Gap between Past Events Carousel

### ISSUE THREAD

**Issue by Safnaj** [sliit-foss/sliitfoss#374]
Can have different numbers of Slides as per the device.
Can increase the width of Each slide.

<img width="1237" alt="Screenshot 2022-10-22 at 12 54 54 AM" src="https://user-images.githubusercontent.com/37530024/197274052-e5c01a0f-5e59-43b7-bb8a-efd2c99b5294.png">

**Comment by JhoanAlvear** [comment]
i can help, assigne to me
