### ISSUE TITLE
FOSS Logo getting hide in responsive.

### ISSUE THREAD

**Issue by Safnaj** [sliit-foss/sliitfoss#38]
<img width="718" alt="Screenshot 2020-11-17 at 5 05 41 PM" src="https://user-images.githubusercontent.com/37530024/99385538-218f3a80-28f7-11eb-893d-68dbdefd789c.png">

**Comment by Shehanka** [comment]
@Bawanthathilan can you work on this?

**Comment by Bawanthathilan** [comment]
yes i'll do it  @Shehanka
