### ISSUE TITLE
The Color Scheme

### ISSUE THREAD

**Issue by Shehanka** [sliit-foss/sliitfoss#4]

**Comment by Safnaj** [comment]
Violet -  **#7700cf**

**Comment by Shehanka** [comment]
> #7700cf

#5a00cf

**Comment by Sewvandiii** [comment]
#BB8FCE

**Comment by Sewvandiii** [comment]
#D7BDE2

**Comment by Kushiya** [comment]
> #BB8FCE

Not suitable for primary color

**Comment by Kushiya** [comment]
Choose an one main color and generate variations from this > https://noeldelgado.github.io/shadowlord

**Comment by Sewvandiii** [comment]
@Kushiya #FFDF61 Yellow

**Comment by Sewvandiii** [comment]
https://uigradients.com/#Windy 😁

**Comment by Kushiya** [comment]
> https://uigradients.com/#Windy 😁

Light wadi ☹️

**Comment by Shehanka** [comment]
<img width="938" alt="Screenshot 2020-10-27 at 19 04 30" src="https://user-images.githubusercontent.com/19349315/97308786-43ad1400-1887-11eb-9cfb-dceede79c8be.png">

**Comment by Safnaj** [comment]
> <img alt="Screenshot 2020-10-27 at 19 04 30" width="938" src="https://user-images.githubusercontent.com/19349315/97308786-43ad1400-1887-11eb-9cfb-dceede79c8be.png">
> 
> @Kushiya @Safnaj @Sewvandiii

1st One 👌

**Comment by SahasR** [comment]
Is the SLIIT FOSS Purple color: #5a5af3 ? 
Saw this in a different section of the web page so used it in the about and contact us page

**Comment by Shehanka** [comment]
@Safnaj
