### ISSUE TITLE
need a proper wireframe

### ISSUE THREAD

**Issue by Dilshan97** [sliit-foss/sliitfoss#40]
anyone can provide the finalized wireframe design for this website?

**Comment by Safnaj** [comment]
[SLIIT_FOSS_Home.pdf](https://github.com/sliit-foss/sliitfoss/files/5654043/SLIIT_FOSS_Home.pdf)

@Dilshan97 Here is the design. 

You can add or change if anything that make the site good looking..!

**Comment by Shehanka** [comment]
I gonna close this @Dilshan97 you can proceed with wireframe
