### ISSUE TITLE
Complete Contact Us Page

### ISSUE THREAD

**Issue by Shehanka** [sliit-foss/sliitfoss#52]
- [x] Make UIs like this (About - https://bootstrapmade.com/demo/Resi/ )
- [ ] Fix UIs css, Get help from @Bawanthathilan 
- [x] Fill the details (email address , contact details, etc..)

**Comment by Shehanka** [comment]
@SahasR Here's the isse

**Comment by SahasR** [comment]
@Shehanka okay I will see what I can do

**Comment by SahasR** [comment]
Okay so I think Contact Page is done (Atleast the front end of it). What do you want done in the About page?

**Comment by Safnaj** [comment]
About should contain the history of SLIIT FOSS Community and What we do. We can have FAQ also there.

**Comment by SahasR** [comment]
@Safnaj is there any website right now with this info so I can change it up a bit and migrate it over to this About page.

**Comment by Safnaj** [comment]
@Sewvandiii can u help him on the data collection ?
