### ISSUE TITLE
Improve Contact Us page

### ISSUE THREAD

**Issue by Safnaj** [sliit-foss/sliitfoss#68]
Improve the contact us page with two column contact box. One column can contain out social links.

<img width="607" alt="Screenshot 2020-12-28 at 7 01 46 PM" src="https://user-images.githubusercontent.com/37530024/103217665-235d0c80-493f-11eb-840a-5326fe796e9e.png">

**Comment by Bawanthathilan** [comment]
https://github.com/sliit-foss/sliitfoss/pull/93
