### ISSUE TITLE
Navbar toggle misplaced in mobile view

### ISSUE THREAD

**Issue by Safnaj** [sliit-foss/sliitfoss#90]
Navbar toggle is misplaced for mobile view. It should be in right top corner.

![image](https://user-images.githubusercontent.com/37530024/104092243-addf2d80-52a8-11eb-9987-1af6a382e56f.png)

**Comment by SahasR** [comment]
Issue is because the logo size too big, will have to resize logo and then navbar should go up 

![WhatsApp Image 2021-01-10 at 14 42 02](https://user-images.githubusercontent.com/56167123/104118956-74fb9300-5352-11eb-876b-8c26cefde82a.jpeg)

**Comment by Safnaj** [comment]
This is not fixed yet. You have accidently closed the PR#91

**Comment by Shehanka** [comment]
sorry.
