### ISSUE TITLE
Fix all typography errors in site

### ISSUE THREAD

**Issue by Shehanka** [sliit-foss/sliitfoss#99]
Style fonts 

<img width="1221" alt="Screenshot 2021-01-16 at 22 18 14" src="https://user-images.githubusercontent.com/19349315/104817686-c7541c80-5848-11eb-9f6a-08b0bf8ec511.png">

**Comment by nisalrenuja** [comment]
I will fix this issue

**Comment by Shehanka** [comment]
This issue has not fixed yet

**Comment by ChathushkaRodrigo** [comment]
Can I help with this typography issue?
